### ISSUE TITLE
更详细的教程？

### ISSUE THREAD

**Issue by feioi2** [fkxxyz/ssfconv#3]
很喜欢你的项目，但不会用🤒️
能不能出一个更详细的小白教程……有视频会更好。
谢谢啦！🙏🏻️

**Comment by fkxxyz** [comment]
哈哈会影响，Windows基本都用不了，除非刚好跨平台，我的项目基本都是 linux 下的，对 linux 命令行熟悉才可以，我本人很久没用过 Windows 了
