### ISSUE TITLE
運行失敗，提示沒有Crypto模塊

### ISSUE THREAD

**Issue by yalegage** [fkxxyz/ssfconv#4]
我不太懂程序，現在用您的rime輸入法，挺好用的，感谢，想进一步用用皮肤，但按教程轉換皮膚失敗。
我用的是manjaro KDE系統，我查了，安裝的有python3.8，系統包管理器中沒有需要的Crypto、pillow、numpy 库，所以就用的pip安裝這些庫，不過安装的时候提示Crypto和numpy库已有，pillow没找到，我查看文件夹下也确实有，但进行到第一步就提示：
  File "./ssfconv", line 4, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
所以不知道怎么办了，能帮忙解决下吗？谢谢！

**Comment by fkxxyz** [comment]
manjaro 属于 arch 系列的发行版，在 arch 系列的发行版下，安装 python-pycryptodome python-pillow python-numpy 这三个软件包就可以了

**Comment by yalegage** [comment]
感谢，已经转换成功，并且用上了我下载的皮肤，真的很不错！🙏🏻️🙏🏻️🙏🏻️
